const all_decks = [
    {
        title: "Madness",
        colors: ["U", "G"],
        tags: ["midrange","self-discard"],
        thumbnail: { name: "Wild Mongrel", set: "ody" },
        cards: [
            { quantity: 4, name: "Aquamoeba", set: "tor" },
            { quantity: 4, name: "Arrogant Wurm", set: "tor" },
            { quantity: 4, name: "Basking Rootwalla", set: "tor" },
            { quantity: 1, name: "Merfolk Looter", set: "exo" },
            { quantity: 1, name: "Squee, Goblin Nabob", set: "mmq" },
            { quantity: 1, name: "Waterfront Bouncer", set: "mmq" },
            { quantity: 4, name: "Wild Mongrel", set: "ody" },
            { quantity: 1, name: "Wonder", set: "jud" },
            { quantity: 4, name: "Careful Study", set: "ody" },
            { quantity: 2, name: "Deep Analysis", set: "tor" },
            { quantity: 2, name: "Roar of the Wurm", set: "ody" },
            { quantity: 4, name: "Circular Logic", set: "tor" },
            { quantity: 4, name: "Daze", set: "nem" },
            { quantity: 4, name: "Frantic Search", set: "ulg" },
            { quantity: 1, name: "Centaur Garden", set: "ody" },
            { quantity: 1, name: "Cephalid Coliseum", set: "ody" },
            { quantity: 7, name: "Island", set: "7ed" },
            { quantity: 7, name: "Forest", set: "7ed" },
            { quantity: 4, name: "Yavimaya Coast", set: "apc" },
        ]
    },
    {
        title: "Broccoli Soup",
        colors: ["B", "G"],
        tags: ["aggro"],
        thumbnail: { name: "Dauthi Slayer", set: "tmp" },
        cards: [
            { quantity: 1, name: "Bad Moon", set: "tsb" },
            { quantity: 1, name: "Call of the Herd", set: "ody" },
            { quantity: 4, name: "Carnophage", set: "exo" },
            { quantity: 2, name: "Darigaaz's Caldera", set: "pls" },
            { quantity: 4, name: "Dark Ritual", set: "mmq" },
            { quantity: 2, name: "Dauthi Horror", set: "tmp" },
            { quantity: 2, name: "Dauthi Slayer", set: "tmp" },
            { quantity: 1, name: "Drinker of Sorrow", set: "lgn" },
            { quantity: 4, name: "Duress", set: "usg" },
            { quantity: 1, name: "Flesh Reaver", set: "usg" },
            { quantity: 4, name: "Gemstone Mine", set: "wth" },
            { quantity: 1, name: "Grinning Demon", set: "ons" },
            { quantity: 1, name: "Kaervek's Spite", set: "vis" },
            { quantity: 4, name: "Llanowar Wastes", set: "apc" },
            { quantity: 1, name: "Naturalize", set: "ons" },
            { quantity: 1, name: "Phyrexian Negator", set: "wc99" },
            { quantity: 4, name: "Rancor", set: "ulg" },
            { quantity: 1, name: "Rotting Giant", set: "ody" },
            { quantity: 4, name: "Sarcomancy", set: "tmp" },
            { quantity: 4, name: "Skittering Skirge", set: "usg" },
            { quantity: 10, name: "Swamp", set: "tmp" },
            { quantity: 1, name: "Tainted Wood", set: "tor" },
            { quantity: 1, name: "Tempting Wurm", set: "ons" },
            { quantity: 1, name: "Unearth", set: "ulg" },
            { quantity: 1, name: "Wretched Anurid", set: "ons" },
        ]
    },
    {
        title: "Burn",
        colors: ["R"],
        tags: ["aggro"],
        thumbnail: { name: "Jackal Pup", set: "tmp" },
        cards: [
            { quantity: 4, name: "Ball Lightning", set: "4ed" },
            { quantity: 2, name: "Barbarian Ring", set: "ody" },
            { quantity: 4, name: "Bloodstained Mire", set: "ons" },
            { quantity: 2, name: "Cursed Scroll", set: "tmp" },
            { quantity: 4, name: "Fireblast", set: "vis" },
            { quantity: 4, name: "Grim Lavamancer", set: "tor" },
            { quantity: 4, name: "Incinerate", set: "mir" },
            { quantity: 4, name: "Jackal Pup", set: "tmp" },
            { quantity: 1, name: "Lava Dart", set: "jud" },
            { quantity: 4, name: "Lightning Bolt", set: "3ed" },
            { quantity: 4, name: "Mogg Fanatic", set: "tmp" },
            { quantity: 10, name: "Mountain", set: "ons" },
            { quantity: 2, name: "Pyrostatic Pillar", set: "scg" },
            { quantity: 4, name: "Seal of Fire", set: "nem" },
            { quantity: 1, name: "Shock", set: "ons" },
            { quantity: 2, name: "Sulfuric Vortex", set: "scg" },
            { quantity: 4, name: "Wooded Foothills", set: "ons" },
        ]
    },
    {
        title: "Contamination",
        colors: ["B"],
        tags: ["prison", "control"],
        thumbnail: { name: "Contamination", set: "usg" },
        cards: [
            { quantity: 4, name: "Cabal Therapy", set: "jud" },
            { quantity: 1, name: "Chimeric Idol", set: "pcy" },
            { quantity: 2, name: "Contagion", set: "all" },
            { quantity: 4, name: "Contamination", set: "usg" },
            { quantity: 4, name: "Duress", set: "usg" },
            { quantity: 1, name: "Engineered Plague", set: "7ed" },
            { quantity: 4, name: "Innocent Blood", set: "ody" },
            { quantity: 4, name: "Mishra's Factory", set: "4ed" },
            { quantity: 4, name: "Nether Spirit", set: "mmq" },
            { quantity: 2, name: "Phyrexian Furnace", set: "wth" },
            { quantity: 2, name: "Powder Keg", set: "tmp" },
            { quantity: 1, name: "Sickening Dreams", set: "tor" },
            { quantity: 2, name: "Skeletal Scrying", set: "ody" },
            { quantity: 1, name: "Spawning Pool", set: "ulg" },
            { quantity: 1, name: "Spinning Darkness", set: "wth" },
            { quantity: 19, name: "Swamp", set: "ice" },
            { quantity: 4, name: "Zombie Infestation", set: "ody" },
        ]
    },
    {
        title: "D.G. Ale",
        colors: ["W", "B"],
        tags: ["midrange"],
        thumbnail: { name: "Vindicate", set: "apc" },
        cards: [
            { quantity: 1, name: "Bane of the Living", set: "lgn" },
            { quantity: 3, name: "Black Knight", set: "3ed" },
            { quantity: 4, name: "Caves of Koilos", set: "apc" },
            { quantity: 4, name: "Dark Ritual", set: "3ed" },
            { quantity: 1, name: "Death Grasp", set: "apc" },
            { quantity: 1, name: "Desolation Angel", set: "apc" },
            { quantity: 1, name: "Disenchant", set: "ice" },
            { quantity: 4, name: "Duress", set: "7ed" },
            { quantity: 3, name: "Exalted Angel", set: "ons" },
            { quantity: 4, name: "Gerrard's Verdict", set: "apc" },
            { quantity: 3, name: "Nantuko Shade", set: "ody" },
            { quantity: 3, name: "Phyrexian Arena", set: "apc" },
            { quantity: 8, name: "Plains", set: "tmp" },
            { quantity: 10, name: "Swamp", set: "tmp" },
            { quantity: 4, name: "Swords to Plowshares", set: "ice" },
            { quantity: 2, name: "Tainted Field", set: "tor" },
            { quantity: 4, name: "Vindicate", set: "apc" },
        ]
    },
    {
        title: "Elves",
        colors: ["G"],
        tags: ["aggro","combo","tribal"],
        thumbnail: { name: "Priest of Titania", set: "usg" },
        cards: [
            { quantity: 1, name: "Biorhythm", set: "ons" },
            { quantity: 4, name: "Birchlore Rangers", set: "ons" },
            { quantity: 3, name: "Bloodline Shaman", set: "ons" },
            { quantity: 1, name: "Caller of the Claw", set: "lgn" },
            { quantity: 1, name: "Deranged Hermit", set: "ulg" },
            { quantity: 1, name: "Elvish Champion", set: "7ed" },
            { quantity: 12, name: "Forest", set: "usg" },
            { quantity: 1, name: "Fyndhorn Elves", set: "ice" },
            { quantity: 4, name: "Gaea's Cradle", set: "ulg" },
            { quantity: 2, name: "Llanowar Elves", set: "7ed" },
            { quantity: 4, name: "Multani's Acolyte", set: "ulg" },
            { quantity: 4, name: "Priest of Titania", set: "usg" },
            { quantity: 4, name: "Quirion Ranger", set: "vis" },
            { quantity: 1, name: "Recycle", set: "tmp" },
            { quantity: 1, name: "Sylvan Messenger", set: "apc" },
            { quantity: 4, name: "Timberwatch Elf", set: "lgn" },
            { quantity: 1, name: "Wellwisher", set: "ons" },
            { quantity: 4, name: "Wirewood Herald", set: "ons" },
            { quantity: 1, name: "Wirewood Hivemaster", set: "lgn" },
            { quantity: 2, name: "Wirewood Lodge", set: "ons" },
            { quantity: 4, name: "Wirewood Symbiote", set: "scg" },
        ]
    },
    {
        title: "Goblins",
        colors: ["R"],
        tags: ["aggro","tribal"],
        thumbnail: { name: "Goblin Lackey", set: "usg" },
        cards: [
            { quantity: 1, name: "Brightstone Ritual", set: "ons" },
            { quantity: 1, name: "Clickslither", set: "lgn" },
            { quantity: 2, name: "Gempalm Incinerator", set: "lgn" },
            { quantity: 1, name: "Goblin Burrows", set: "ons" },
            { quantity: 1, name: "Goblin King", set: "6ed" },
            { quantity: 4, name: "Goblin Lackey", set: "usg" },
            { quantity: 4, name: "Goblin Matron", set: "usg" },
            { quantity: 4, name: "Goblin Piledriver", set: "ons" },
            { quantity: 4, name: "Goblin Ringleader", set: "apc" },
            { quantity: 1, name: "Goblin Sharpshooter", set: "ons" },
            { quantity: 1, name: "Goblin Tinkerer", set: "mir" },
            { quantity: 1, name: "Goblin War Strike", set: "scg" },
            { quantity: 4, name: "Goblin Warchief", set: "scg" },
            { quantity: 4, name: "Mogg Fanatic", set: "tmp" },
            { quantity: 18, name: "Mountain", set: "ons" },
            { quantity: 4, name: "Rishadan Port", set: "mmq" },
            { quantity: 3, name: "Siege-Gang Commander", set: "scg" },
            { quantity: 2, name: "Skirk Prospector", set: "ons" },
        ]
    },
    {
        title: "Magnivore",
        colors: ["R", "G"],
        tags: ["midrange","land destr."],
        thumbnail: { name: "Magnivore", set: "ody" },
        cards: [
            { quantity: 1, name: "Assault // Battery", set: "inv" },
            { quantity: 4, name: "Call of the Herd", set: "tsb" },
            { quantity: 1, name: "Earthquake", set: "por" },
            { quantity: 4, name: "Firebolt", set: "ody" },
            { quantity: 3, name: "Forest", set: "7ed" },
            { quantity: 1, name: "Ghitu Encampment", set: "ulg" },
            { quantity: 2, name: "Hull Breach", set: "pls" },
            { quantity: 4, name: "Karplusan Forest", set: "7ed" },
            { quantity: 4, name: "Magnivore", set: "ody" },
            { quantity: 1, name: "Mossfire Valley", set: "ody" },
            { quantity: 5, name: "Mountain", set: "7ed" },
            { quantity: 4, name: "Oath of Druids", set: "exo" },
            { quantity: 4, name: "Pillage", set: "all" },
            { quantity: 2, name: "Pyroclasm", set: "ice" },
            { quantity: 4, name: "Rampant Growth", set: "mir" },
            { quantity: 1, name: "Slice and Dice", set: "ons" },
            { quantity: 4, name: "Stone Rain", set: "ice" },
            { quantity: 3, name: "Treetop Village", set: "ulg" },
            { quantity: 4, name: "Wasteland", set: "wc98    " },
            { quantity: 4, name: "Wooded Foothills", set: "ons" },
        ]
    },
    {
        title: "Nic Fit (Rock)",
        colors: ["B", "G"],
        tags: ["midrange"],
        thumbnail: { name: "Spiritmonger", set: "apc" },
        cards: [
            { quantity: 1, name: "Abyssal Gatekeeper", set: "wth" },
            { quantity: 2, name: "Blastoderm", set: "nem" },
            { quantity: 1, name: "Bone Shredder", set: "ulg" },
            { quantity: 4, name: "Cabal Therapy", set: "jud" },
            { quantity: 1, name: "Deranged Hermit", set: "ulg" },
            { quantity: 1, name: "Diabolic Edict", set: "tmp" },
            { quantity: 4, name: "Duress", set: "usg" },
            { quantity: 7, name: "Forest", set: "m13" },
            { quantity: 1, name: "Genesis", set: "jud" },
            { quantity: 1, name: "Graveborn Muse", set: "lgn" },
            { quantity: 1, name: "Krosan Tusker", set: "ons" },
            { quantity: 4, name: "Llanowar Wastes", set: "apc" },
            { quantity: 4, name: "Pernicious Deed", set: "apc" },
            { quantity: 1, name: "Phyrexian Rager", set: "apc" },
            { quantity: 2, name: "Ravenous Baloth", set: "ons" },
            { quantity: 2, name: "Recurring Nightmare", set: "wc98" },
            { quantity: 1, name: "Smother", set: "ons" },
            { quantity: 1, name: "Spiritmonger", set: "apc" },
            { quantity: 6, name: "Swamp", set: "dsk" },
            { quantity: 4, name: "Treetop Village", set: "ulg" },
            { quantity: 4, name: "Veteran Explorer", set: "wth" },
            { quantity: 1, name: "Volrath's Stronghold", set: "wc98" },
            { quantity: 4, name: "Wall of Blossoms", set: "sth" },
            { quantity: 1, name: "Yavimaya Elder", set: "uds" },
            { quantity: 1, name: "Natural Order", set: "vis" },
        ]
    },
    {
        title: "Pit Rack",
        colors: ["B", "R"],
        tags: ["control","discard"],
        thumbnail: { name: "The Rack", set: "4ed" },
        cards: [
            { quantity: 1, name: "Blazing Specter", set: "inv" },
            { quantity: 4, name: "Bloodstained Mire", set: "ons" },
            { quantity: 4, name: "Bottomless Pit", set: "sth" },
            { quantity: 3, name: "Cabal Therapy", set: "jud" },
            { quantity: 1, name: "Chain of Smog", set: "ons" },
            { quantity: 4, name: "Dark Ritual", set: "5ed" },
            { quantity: 4, name: "Duress", set: "7ed" },
            { quantity: 4, name: "Hypnotic Specter", set: "3ed" },
            { quantity: 1, name: "Lavaborn Muse", set: "lgn" },
            { quantity: 4, name: "Lightning Bolt", set: "3ed" },
            { quantity: 4, name: "Mishra's Factory", set: "4ed" },
            { quantity: 1, name: "Mountain", set: "tmp" },
            { quantity: 4, name: "Ravenous Rats", set: "uds" },
            { quantity: 1, name: "Shadowblood Ridge", set: "ody" },
            { quantity: 1, name: "Skeletal Scrying", set: "ody" },
            { quantity: 4, name: "Sulfurous Springs", set: "5ed" },
            { quantity: 7, name: "Swamp", set: "tmp" },
            { quantity: 1, name: "Tainted Peak", set: "tor" },
            { quantity: 3, name: "Terminate", set: "pls" },
            { quantity: 4, name: "The Rack", set: "4ed" },
        ]
    },
    {
        title: "Psychatog",
        colors: ["U", "B"],
        tags: ["control"],
        thumbnail: { name: "Psychatog", set: "ody" },
        cards: [
            { quantity: 4, name: "Accumulated Knowledge", set: "nem" },
            { quantity: 4, name: "Duress", set: "7ed" },
            { quantity: 3, name: "Fact or Fiction", set: "inv" },
            { quantity: 2, name: "Foil", set: "pcy" },
            { quantity: 1, name: "Force Spike", set: "5ed" },
            { quantity: 4, name: "Gush", set: "mmq" },
            { quantity: 8, name: "Island", set: "ody" },
            { quantity: 4, name: "Opt", set: "inv" },
            { quantity: 4, name: "Polluted Delta", set: "ons" },
            { quantity: 4, name: "Portent", set: "ice" },
            { quantity: 4, name: "Psychatog", set: "ody" },
            { quantity: 1, name: "Shadowmage Infiltrator", set: "tsb" },
            { quantity: 2, name: "Smother", set: "ons" },
            { quantity: 1, name: "Snuff Out", set: "mmq" },
            { quantity: 7, name: "Swamp", set: "ody" },
            { quantity: 4, name: "Underground River", set: "wc97" },
            { quantity: 2, name: "Vendetta", set: "mmq" },
            { quantity: 1, name: "Wonder", set: "jud" },
        ]
    },
    {
        title: "Root Stompy",
        colors: ["G"],
        tags: ["aggro"],
        thumbnail: { name: "Pouncing Jaguar", set: "pal99" },
        cards: [
            { quantity: 1, name: "Albino Troll", set: "f02" },
            { quantity: 2, name: "Bounty of the Hunt", set: "all" },
            { quantity: 1, name: "Druid Lyrist", set: "ody" },
            { quantity: 4, name: "Elvish Spirit Guide", set: "all" },
            { quantity: 4, name: "Forest", set: "4bb" },
            { quantity: 3, name: "Forest", set: "4bb" },
            { quantity: 3, name: "Forest", set: "4bb" },
            { quantity: 4, name: "Fyndhorn Elves", set: "ice" },
            { quantity: 4, name: "Giant Growth", set: "ice" },
            { quantity: 4, name: "Invigorate", set: "mmq" },
            { quantity: 4, name: "Land Grant", set: "mmq" },
            { quantity: 1, name: "Mtenda Lion", set: "mir" },
            { quantity: 1, name: "Naturalize", set: "ons" },
            { quantity: 1, name: "Pouncing Jaguar", set: "pal99" },
            { quantity: 4, name: "Rancor", set: "ulg" },
            { quantity: 4, name: "River Boa", set: "vis" },
            { quantity: 4, name: "Rogue Elephant", set: "wth" },
            { quantity: 4, name: "Root Maze", set: "tmp" },
            { quantity: 1, name: "Scavenger Folk", set: "7ed" },
            { quantity: 1, name: "Skyshroud Elite", set: "exo" },
            { quantity: 4, name: "Vine Dryad", set: "mmq" },
            { quantity: 1, name: "Wild Dogs", set: "usg" },
        ]
    },
    {
        title: "Standstill",
        colors: ["W", "U"],
        tags: ["control"],
        thumbnail: { name: "Standstill", set: "ody" },
        cards: [
            { quantity: 1, name: "Absorb", set: "inv" },
            { quantity: 1, name: "Adarkar Wastes", set: "6ed" },
            { quantity: 1, name: "Adarkar Wastes", set: "5ed" },
            { quantity: 2, name: "Coastal Tower", set: "inv" },
            { quantity: 2, name: "Decree of Justice", set: "scg" },
            { quantity: 1, name: "Dismantling Blow", set: "inv" },
            { quantity: 1, name: "Dominate", set: "nem" },
            { quantity: 2, name: "Fact or Fiction", set: "inv" },
            { quantity: 2, name: "Faerie Conclave", set: "ulg" },
            { quantity: 4, name: "Flooded Strand", set: "ons" },
            { quantity: 1, name: "Forbid", set: "wc98" },
            { quantity: 1, name: "Forbidding Watchtower", set: "ulg" },
            { quantity: 4, name: "Impulse", set: "dmr" },
            { quantity: 5, name: "Island", set: "tmp" },
            { quantity: 1, name: "Kirtar's Desire", set: "ody" },
            { quantity: 2, name: "Mana Leak", set: "sth" },
            { quantity: 2, name: "Masticore", set: "uds" },
            { quantity: 1, name: "Miscalculation", set: "ulg" },
            { quantity: 4, name: "Mishra's Factory", set: "4ed" },
            { quantity: 1, name: "Mobilization", set: "ons" },
            { quantity: 4, name: "Plains", set: "tmp" },
            { quantity: 2, name: "Prohibit", set: "inv" },
            { quantity: 1, name: "Quicksand", set: "vis" },
            { quantity: 2, name: "Seal of Cleansing", set: "nem" },
            { quantity: 1, name: "Skycloud Expanse", set: "brc" },
            { quantity: 3, name: "Standstill", set: "ody" },
            { quantity: 1, name: "Stroke of Genius", set: "usg" },
            { quantity: 4, name: "Swords to Plowshares", set: "4ed" },
            { quantity: 1, name: "Trade Routes", set: "mmq" },
            { quantity: 2, name: "Wrath of God", set: "3ed" },
        ]
    },
    {
        title: "Stasis",
        colors: ["U"],
        tags: ["prison", "control"],
        thumbnail: { name: "Stasis", set: "4ed" },
        cards: [
            { quantity: 1, name: "Annul", set: "usg" },
            { quantity: 4, name: "Black Vise", set: "4ed" },
            { quantity: 4, name: "Chain of Vapor", set: "ons" },
            { quantity: 1, name: "Chronatog", set: "vis" },
            { quantity: 4, name: "Counterspell", set: "mmq" },
            { quantity: 3, name: "Daze", set: "nem" },
            { quantity: 1, name: "Flash of Insight", set: "jud" },
            { quantity: 1, name: "Foil", set: "pcy" },
            { quantity: 4, name: "Forsaken City", set: "pls" },
            { quantity: 4, name: "Gush", set: "mmq" },
            { quantity: 4, name: "Impulse", set: "dmr" },
            { quantity: 18, name: "Island", set: "tmp" },
            { quantity: 1, name: "Mana Short", set: "6ed" },
            { quantity: 4, name: "Stasis", set: "4ed" },
            { quantity: 3, name: "Thwart", set: "mmq" },
            { quantity: 1, name: "Upheaval", set: "wc02" },
        ]
    },
    {
        title: "Clerics",
        colors: ["W"],
        tags: ["midrange","tribal"],
        thumbnail: { name: "Mother of Runes", set: "ulg" },
        cards: [
            { quantity: 2, name: "Abolish", set: "pcy" },
            { quantity: 2, name: "Armageddon", set: "ptc" },
            { quantity: 4, name: "Beloved Chaplain", set: "ody" },
            { quantity: 4, name: "Daru Spiritualist", set: "scg" },
            { quantity: 2, name: "Glowrider", set: "lgn" },
            { quantity: 1, name: "Kor Haven", set: "nem" },
            { quantity: 2, name: "Master Apothecary", set: "ody" },
            { quantity: 4, name: "Mother of Runes", set: "ulg" },
            { quantity: 12, name: "Plains", set: "tmp" },
            { quantity: 1, name: "Remote Farm", set: "mmq" },
            { quantity: 1, name: "Reverent Mantra", set: "mmq" },
            { quantity: 2, name: "Secluded Steppe", set: "ons" },
            { quantity: 4, name: "Shaman en-Kor", set: "sth" },
            { quantity: 2, name: "Shared Triumph", set: "ons" },
            { quantity: 2, name: "Soltari Monk", set: "tmp" },
            { quantity: 2, name: "Soltari Priest", set: "tmp" },
            { quantity: 3, name: "Starlit Sanctum", set: "ons" },
            { quantity: 4, name: "Swords to Plowshares", set: "4ed" },
            { quantity: 2, name: "True Believer", set: "ons" },
            { quantity: 4, name: "Weathered Wayfarer", set: "ons" },
        ]
    },
    {
        title: "Astral Slide",
        colors: ["W", "G"],
        tags: ["midrange"],
        thumbnail: { name: "Astral Slide", set: "ons" },
        cards: [
            { quantity: 1, name: "Anurid Brushhopper", set: "jud" },
            { quantity: 3, name: "Astral Slide", set: "ons" },
            { quantity: 1, name: "Auramancer", set: "ody" },
            { quantity: 3, name: "Cartographer", set: "ody" },
            { quantity: 1, name: "Deranged Hermit", set: "ulg" },
            { quantity: 4, name: "Eternal Dragon", set: "scg" },
            { quantity: 5, name: "Forest", set: "tmp" },
            { quantity: 2, name: "Karmic Guide", set: "ulg" },
            { quantity: 1, name: "Krosan Tusker", set: "ons" },
            { quantity: 1, name: "Mystic Enforcer", set: "ody" },
            { quantity: 2, name: "Nantuko Monastery", set: "jud" },
            { quantity: 6, name: "Plains", set: "tmp" },
            { quantity: 4, name: "Renewed Faith", set: "ons" },
            { quantity: 1, name: "Seal of Cleansing", set: "nem" },
            { quantity: 4, name: "Secluded Steppe", set: "ons" },
            { quantity: 1, name: "Sterling Grove", set: "inv" },
            { quantity: 4, name: "Swords to Plowshares", set: "ice" },
            { quantity: 2, name: "Sylvan Library", set: "4ed" },
            { quantity: 4, name: "Tranquil Thicket", set: "ons" },
            { quantity: 1, name: "Uktabi Orangutan", set: "vis" },
            { quantity: 4, name: "Wall of Blossoms", set: "sth" },
            { quantity: 3, name: "Windswept Heath", set: "mh3" },
            { quantity: 2, name: "Wrath of God", set: "4ed" },
        ]
    },
    {
        title: "Mono Brown",
        colors: ["1"],
        tags: ["prison", "control"],
        thumbnail: { name: "Metalworker", set: "wc00" },
        cards: [
            { quantity: 4, name: "Ancient Tomb", set: "wc99" },
            { quantity: 3, name: "Black Vise", set: "ptc" },
            { quantity: 4, name: "City of Traitors", set: "wc99" },
            { quantity: 1, name: "Dust Bowl", set: "wc00" },
            { quantity: 2, name: "Karn, Silver Golem", set: "wc99" },
            { quantity: 2, name: "Masticore", set: "wc00" },
            { quantity: 4, name: "Metalworker", set: "wc00" },
            { quantity: 4, name: "Mind Stone", set: "wc97" },
            { quantity: 4, name: "Mishra's Factory", set: "ptc" },
            { quantity: 2, name: "Mishra's Helix", set: "wc00" },
            { quantity: 4, name: "Powder Keg", set: "wc99" },
            { quantity: 4, name: "Rishadan Port", set: "wc01" },
            { quantity: 3, name: "Smokestack", set: "usg" },
            { quantity: 4, name: "Sphere of Resistance", set: "wc99" },
            { quantity: 4, name: "Tangle Wire", set: "wc00" },
            { quantity: 4, name: "Thran Dynamo", set: "wc99" },
            { quantity: 4, name: "Wasteland", set: "wc98" },
            { quantity: 3, name: "Winter Orb", set: "ptc" },
        ]
    },
    {
        title: "Survival",
        colors: ["G"],
        tags: ["combo", "midrange"],
        thumbnail: { name: "Survival of the Fittest", set: "wc98" },
        cards: [
            { quantity: 1, name: "Anger", set: "jud" },
            { quantity: 1, name: "Avalanche Riders", set: "wc99" },
            { quantity: 4, name: "Birds of Paradise", set: "wc00" },
            { quantity: 1, name: "Bloodfire Dwarf", set: "apc" },
            { quantity: 1, name: "Chartooth Cougar", set: "scg" },
            { quantity: 1, name: "City of Brass", set: "wc97" },
            { quantity: 1, name: "City of Brass", set: "wc98" },
            { quantity: 1, name: "Flametongue Kavu", set: "wc02" },
            { quantity: 8, name: "Forest", set: "wc02" },
            { quantity: 1, name: "Genesis", set: "wc02" },
            { quantity: 1, name: "Horned Kavu", set: "pls" },
            { quantity: 1, name: "Kamahl, Fist of Krosa", set: "ons" },
            { quantity: 4, name: "Karplusan Forest", set: "wc02" },
            { quantity: 4, name: "Llanowar Elves", set: "wc02" },
            { quantity: 1, name: "Masticore", set: "wc00" },
            { quantity: 2, name: "Mountain", set: "wc00" },
            { quantity: 1, name: "Nantuko Vigilante", set: "lgn" },
            { quantity: 1, name: "Phantom Nishoba", set: "jud" },
            { quantity: 1, name: "Ravenous Baloth", set: "ons" },
            { quantity: 1, name: "Scavenger Folk", set: "5ed" },
            { quantity: 1, name: "Silvos, Rogue Elemental", set: "ons" },
            { quantity: 1, name: "Spike Feeder", set: "wc98" },
            { quantity: 1, name: "Squee, Goblin Nabob", set: "mmq" },
            { quantity: 1, name: "Stampeding Wildebeests", set: "vis" },
            { quantity: 4, name: "Survival of the Fittest", set: "wc98" },
            { quantity: 1, name: "Thornscape Battlemage", set: "wc02" },
            { quantity: 1, name: "Thunderscape Battlemage", set: "pls" },
            { quantity: 1, name: "Tradewind Rider", set: "wc98" },
            { quantity: 4, name: "Wall of Roots", set: "wc98" },
            { quantity: 4, name: "Wooded Foothills", set: "ons" },
            { quantity: 1, name: "Natural Order", set: "por" },
            { quantity: 1, name: "Yavimaya Granger", set: "ulg" }
        ]
    },
    {
        title: "Sideboard",
        colors: ["W", "U", "B", "R", "G"],
        tags: [],
        thumbnail: { name: "Tormod's Crypt", set: "chr" },
        cards: [
            { quantity: 2, name: "Anarchy", set: "ice" },
            { quantity: 2, name: "Annul", set: "usg" },
            { quantity: 2, name: "Aura of Silence", set: "wth" },
            { quantity: 1, name: "Boil", set: "tmp" },
            { quantity: 1, name: "Blue Elemental Blast", set: "3ed" },
            { quantity: 2, name: "Carpet of Flowers", set: "usg" },
            { quantity: 1, name: "Chill", set: "tmp" },
            { quantity: 2, name: "Choke", set: "tmp" },
            { quantity: 2, name: "Circle of Protection: Red", set: "tmp" },
            { quantity: 1, name: "Coffin Purge", set: "ody" },
            { quantity: 1, name: "Compost", set: "uds" },
            { quantity: 1, name: "Corrosion", set: "vis" },
            { quantity: 1, name: "Crash", set: "mmq" },
            { quantity: 2, name: "Crumble", set: "4ed" },
            { quantity: 2, name: "Crumbling Sanctuary", set: "mmq" },
            { quantity: 2, name: "Defense Grid", set: "ulg" },
            { quantity: 1, name: "Devoted Caretaker", set: "ody" },
            { quantity: 2, name: "Disenchant", set: "tmp" },
            { quantity: 3, name: "Disenchant", set: "6ed" },
            { quantity: 2, name: "Dystopia", set: "all" },
            { quantity: 2, name: "Emerald Charm", set: "vis" },
            { quantity: 3, name: "Engineered Plague", set: "ulg" },
            { quantity: 2, name: "Ensnaring Bridge", set: "sth" },
            { quantity: 1, name: "Fire Covenant", set: "ice" },
            { quantity: 1, name: "Flashfires", set: "6ed" },
            { quantity: 1, name: "Funeral Pyre", set: "jud" },
            { quantity: 1, name: "Gaea's Blessing", set: "wth" },
            { quantity: 2, name: "Gempalm Incinerator", set: "lgn" },
            { quantity: 3, name: "Gloom", set: "3ed" },
            { quantity: 1, name: "Goblin Tinkerer", set: "mir" },
            { quantity: 1, name: "Hibernation", set: "usg" },
            { quantity: 1, name: "Hibernation", set: "7ed" },
            { quantity: 2, name: "Hydroblast", set: "ice" },
            { quantity: 2, name: "Illumination", set: "mir" },
            { quantity: 1, name: "Monk Idealist", set: "usg" },
            { quantity: 1, name: "Monk Realist", set: "usg" },
            { quantity: 3, name: "Naturalize", set: "ons" },
            { quantity: 1, name: "Nevinyrral's Disk", set: "wc97" },
            { quantity: 2, name: "Overload", set: "inv" },
            { quantity: 2, name: "Perish", set: "tmp" },
            { quantity: 2, name: "Plague Spitter", set: "inv" },
            { quantity: 1, name: "Presence of the Master", set: "usg" },
            { quantity: 2, name: "Pyroblast", set: "ice" },
            { quantity: 1, name: "Pyroclasm", set: "7ed" },
            { quantity: 1, name: "Red Elemental Blast", set: "3ed" },
            { quantity: 1, name: "Red Elemental Blast", set: "4ed" },
            { quantity: 1, name: "Rushing River", set: "pls" },
            { quantity: 2, name: "Rushwood Legate", set: "mmq" },
            { quantity: 2, name: "Sacred Ground", set: "sth" },
            { quantity: 1, name: "Seal of Cleansing", set: "nem" },
            { quantity: 2, name: "Soltari Priest", set: "tsb" },
            { quantity: 1, name: "Spike Feeder", set: "sth" },
            { quantity: 2, name: "Spreading Algae", set: "usg" },
            { quantity: 1, name: "Stromgald Cabal", set: "ice" },
            { quantity: 1, name: "Teferi's Response", set: "inv" },
            { quantity: 1, name: "Terminate", set: "pls" },
            { quantity: 2, name: "Tormod's Crypt", set: "chr" },
            { quantity: 3, name: "Tranquil Domain", set: "mir" },
            { quantity: 1, name: "True Believer", set: "ons" },
            { quantity: 1, name: "Uktabi Orangutan", set: "wc99" },
            { quantity: 1, name: "Vendetta", set: "mmq" },
            { quantity: 1, name: "Warmth", set: "tmp" },
            { quantity: 1, name: "Waterfront Bouncer", set: "mmq" },
            { quantity: 2, name: "Wing Snare", set: "ulg" },
            { quantity: 1, name: "Wrath of God", set: "7ed" },
            { quantity: 1, name: "Zuran Orb", set: "ice" },
        ]
    },
];
